[package]
name = "big_bro"
version = "0.1.0"
edition = "2024"


[dependencies]
kovi = "0.11.7"

kovi-plugin-expand-napcat = "0.3.1"
chrono = "0.4.40"
crc32fast = { version = "1.4.2" }

serde = { version = "1.0.218", features = ["derive"] }

